DO NOT MERGE: fix build breakage
fix klp-dev only build breakage.

  frameworks/native/libs/input/Input.cpp: In member function 'android::status_t android::MotionEvent::readFromParcel(android::Parcel*)':
  frameworks/native/libs/input/Input.cpp:494:47: error: 'UINT16_MAX' was not declared in this scope

Bug: 23905002
Change-Id: I4b6b864ca64d39a8873d045a61e0ddaea2ab9109
(cherry picked from commit 834ac204ce52d874cdd7ae921e5a4d85c5e42c52)

Conflicts:
	include/input/Input.h